ALTER TABLE `TBBANCO`
  ADD PRIMARY KEY (`CODIGOBANCO`);

--
-- Indexes for table `TBBANCOEMPRESA`
--
ALTER TABLE `TBBANCOEMPRESA`
  ADD PRIMARY KEY (`CODIGOEMPRESA`,`CODIGOBANCO`);

--
-- Indexes for table `TBBOLETO`
--
ALTER TABLE `TBBOLETO`
  ADD PRIMARY KEY (`COD_BOLETO`);

--
-- Indexes for table `TBBOLETOEMAILXHISTORICO`
--
ALTER TABLE `TBBOLETOEMAILXHISTORICO`
  ADD PRIMARY KEY (`CODTBBOLETOEMAILXHISTORICO`);

--
-- Indexes for table `TBBOLETOXHISTORICOS`
--
ALTER TABLE `TBBOLETOXHISTORICOS`
  ADD PRIMARY KEY (`COD_BOLETOXHISTORICOS`);

--
-- Indexes for table `TBCENTROCUSTO`
--
ALTER TABLE `TBCENTROCUSTO`
  ADD PRIMARY KEY (`CODIGOEMPRESA`,`CODIGOCCUSTO`);

--
-- Indexes for table `TBCNAE`
--
-- ALTER TABLE `TBCNAE`
--   ADD PRIMARY KEY (`CODIGOCNAE`);

--
-- Indexes for table `TBCOLABORADOR`
--
ALTER TABLE `TBCOLABORADOR`
  ADD PRIMARY KEY (`CODIGOCOLABORADOR`);

--
-- Indexes for table `TBCOMPXOBRIG`
--
ALTER TABLE `TBCOMPXOBRIG`
  ADD PRIMARY KEY (`CODCOMPXOBRIG`);

--
-- Indexes for table `TBEMPRESA`
--
ALTER TABLE `TBEMPRESA`
  ADD PRIMARY KEY (`CODIGOEMPRESA`);

--
-- Indexes for table `TBEMPRESAPRODUTO`
--
ALTER TABLE `TBEMPRESAPRODUTO`
  ADD PRIMARY KEY (`CODIGOEMPRESA`,`CODIGOPRODUTO`,`DVG`);

--
-- Indexes for table `TBEMPRESAUSUARIO`
--
ALTER TABLE `TBEMPRESAUSUARIO`
  ADD PRIMARY KEY (`CODIGO_USUARIO`,`CODIGOPRODUTO`,`CODIGOEMPRESA`,`CODIGOSUBPRODUTO`);

--
-- Indexes for table `TBEMPRESAXARQUIVOS`
--
ALTER TABLE `TBEMPRESAXARQUIVOS`
  ADD PRIMARY KEY (`COD_EMPRESAXARQUIVOS`);

--
-- Indexes for table `TBEMPRESAXCCEMAIL`
--
ALTER TABLE `TBEMPRESAXCCEMAIL`
  ADD PRIMARY KEY (`COD_CCEMAIL`);

--
-- Indexes for table `TBEMPRESA_IMPORTACOES`
--
ALTER TABLE `TBEMPRESA_IMPORTACOES`
  ADD PRIMARY KEY (`CODIGOEMPRESA`);

--
-- Indexes for table `TBEMPRESA_OBRIGACOES`
--
ALTER TABLE `TBEMPRESA_OBRIGACOES`
  ADD PRIMARY KEY (`CODIGOEMPRESA`,`CODIGOOBRIGACAO`);

--
-- Indexes for table `TBEMPRESA_SINDICATO`
--
ALTER TABLE `TBEMPRESA_SINDICATO`
  ADD PRIMARY KEY (`CODIGOEMPRESA`,`CODIGOSINDICATO`);

--
-- Indexes for table `TBESFERAOBRIGACAO`
--
ALTER TABLE `TBESFERAOBRIGACAO`
  ADD PRIMARY KEY (`CODIGOESFERAOBRIGACAO`);

--
-- Indexes for table `TBFORNEC`
--
ALTER TABLE `TBFORNEC`
  ADD PRIMARY KEY (`empresa`,`CodigoFornecedor`);

--
-- Indexes for table `TBFORNECEDOR`
--
ALTER TABLE `TBFORNECEDOR`
  ADD PRIMARY KEY (`CODIGOEMPRESA`,`CODIGOFORNECEDOR`);

--
-- Indexes for table `TBFORNECEDORX`
--
ALTER TABLE `TBFORNECEDORX`
  ADD PRIMARY KEY (`Codigo Fornecedor`);

--
-- Indexes for table `TBINDICEREAJUSTE`
--
ALTER TABLE `TBINDICEREAJUSTE`
  ADD PRIMARY KEY (`CODIGOINDICEREAJUSTE`);

--
-- Indexes for table `TBLOG`
--
ALTER TABLE `TBLOG`
  ADD PRIMARY KEY (`CODIGOLOG`);

--
-- Indexes for table `TBMOVIMENTACAO`
--
ALTER TABLE `TBMOVIMENTACAO`
  ADD PRIMARY KEY (`NUMLANCTO`);

--
-- Indexes for table `TBMUNICIPIO`
--
ALTER TABLE `TBMUNICIPIO`
  ADD PRIMARY KEY (`CODIGOMUNICIPIO`);

--
-- Indexes for table `TBOBRIGACOES`
--
ALTER TABLE `TBOBRIGACOES`
  ADD PRIMARY KEY (`CODIGOOBRIGACAO`);

--
-- Indexes for table `TBOBRIGACOESMENSAL`
--
ALTER TABLE `TBOBRIGACOESMENSAL`
  ADD KEY `COMPETENCIA` (`COMPETENCIA`);

--
-- Indexes for table `TBORIGEMOBRIGACAO`
--
ALTER TABLE `TBORIGEMOBRIGACAO`
  ADD PRIMARY KEY (`CODIGOORIGEM`);

--
-- Indexes for table `TBPERIODICIDADE`
--
ALTER TABLE `TBPERIODICIDADE`
  ADD PRIMARY KEY (`CODIGOPERIODICIDADE`);

--
-- Indexes for table `TBPLANOCONTAS`
--
ALTER TABLE `TBPLANOCONTAS`
  ADD PRIMARY KEY (`CODIGOEMPRESA`,`CODIGOPLANO`);

--
-- Indexes for table `TBPLCONTA`
--
ALTER TABLE `TBPLCONTA`
  ADD PRIMARY KEY (`CODIGOEMPRESA`,`CodigoConta`);

--
-- Indexes for table `TBPRODUTO`
--
ALTER TABLE `TBPRODUTO`
  ADD PRIMARY KEY (`CODIGOPRODUTO`);

--
-- Indexes for table `TBPRODUTOSUBPRODUTO`
--
ALTER TABLE `TBPRODUTOSUBPRODUTO`
  ADD PRIMARY KEY (`CODIGOPRODUTO`,`CODIGOSUBPRODUTO`);

--
-- Indexes for table `TBRESPONSAVEL_EMPRESA`
--
ALTER TABLE `TBRESPONSAVEL_EMPRESA`
  ADD PRIMARY KEY (`CODIGOEMPRESA`,`CODIGOCOLABORADOR`);

--
-- Indexes for table `TBSETOR`
--
ALTER TABLE `TBSETOR`
  ADD PRIMARY KEY (`CODIGOSETOR`);

--
-- Indexes for table `TBSETORFTP`
--
ALTER TABLE `TBSETORFTP`
  ADD PRIMARY KEY (`CODIGOSETOR`,`NOMEPASTA`);

--
-- Indexes for table `TBSINDICATO`
--
ALTER TABLE `TBSINDICATO`
  ADD PRIMARY KEY (`CODIGOSINDICATO`);

--
-- Indexes for table `TBSITUACAO`
--
ALTER TABLE `TBSITUACAO`
  ADD PRIMARY KEY (`CODIGOSITUACAO`);

--
-- Indexes for table `TBSTATUS`
--
ALTER TABLE `TBSTATUS`
  ADD PRIMARY KEY (`COD_STATUS`);

--
-- Indexes for table `TBSUBPRODUTO`
--
ALTER TABLE `TBSUBPRODUTO`
  ADD PRIMARY KEY (`CODIGOSUBPRODUTO`);

--
-- Indexes for table `TBTEMP`
--
ALTER TABLE `TBTEMP`
  ADD PRIMARY KEY (`COD`);

--
-- Indexes for table `TBTIPOCERTIFICADO`
--
ALTER TABLE `TBTIPOCERTIFICADO`
  ADD PRIMARY KEY (`IDTIPOCERT`);

--
-- Indexes for table `TBTIPOFATURAMENTO`
--
ALTER TABLE `TBTIPOFATURAMENTO`
  ADD PRIMARY KEY (`CODIGOTPFATURAMENTO`);

--
-- Indexes for table `TBTIPOOBRIGACAO`
--
ALTER TABLE `TBTIPOOBRIGACAO`
  ADD PRIMARY KEY (`CODIGOTIPOOBRIGACAO`);

--
-- Indexes for table `TBTRIBUTACAO`
--
ALTER TABLE `TBTRIBUTACAO`
  ADD PRIMARY KEY (`CODIGOTRIBUTACAO`);

--
-- Indexes for table `TBUSUARIO`
--
ALTER TABLE `TBUSUARIO`
  ADD PRIMARY KEY (`CODIGO_USUARIO`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `TBBOLETO`
--
ALTER TABLE `TBBOLETO`
  MODIFY `COD_BOLETO` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=549;

--
-- AUTO_INCREMENT for table `TBBOLETOEMAILXHISTORICO`
--
ALTER TABLE `TBBOLETOEMAILXHISTORICO`
  MODIFY `CODTBBOLETOEMAILXHISTORICO` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=10444;

--
-- AUTO_INCREMENT for table `TBBOLETOXHISTORICOS`
--
ALTER TABLE `TBBOLETOXHISTORICOS`
  MODIFY `COD_BOLETOXHISTORICOS` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=551;

--
-- AUTO_INCREMENT for table `TBCOLABORADOR`
--
ALTER TABLE `TBCOLABORADOR`
  MODIFY `CODIGOCOLABORADOR` mediumint(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=27;

--
-- AUTO_INCREMENT for table `TBCOMPXOBRIG`
--
ALTER TABLE `TBCOMPXOBRIG`
  MODIFY `CODCOMPXOBRIG` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=721;

--
-- AUTO_INCREMENT for table `TBEMPRESA`
--
ALTER TABLE `TBEMPRESA`
  MODIFY `CODIGOEMPRESA` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=1337;

--
-- AUTO_INCREMENT for table `TBEMPRESAXARQUIVOS`
--
ALTER TABLE `TBEMPRESAXARQUIVOS`
  MODIFY `COD_EMPRESAXARQUIVOS` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=18078;

--
-- AUTO_INCREMENT for table `TBEMPRESAXCCEMAIL`
--
ALTER TABLE `TBEMPRESAXCCEMAIL`
  MODIFY `COD_CCEMAIL` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=842;

--
-- AUTO_INCREMENT for table `TBESFERAOBRIGACAO`
--
ALTER TABLE `TBESFERAOBRIGACAO`
  MODIFY `CODIGOESFERAOBRIGACAO` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=5;

--
-- AUTO_INCREMENT for table `TBFORNECEDORX`
--
ALTER TABLE `TBFORNECEDORX`
  MODIFY `Codigo Fornecedor` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=79;

--
-- AUTO_INCREMENT for table `TBINDICEREAJUSTE`
--
ALTER TABLE `TBINDICEREAJUSTE`
  MODIFY `CODIGOINDICEREAJUSTE` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=6;

--
-- AUTO_INCREMENT for table `TBLOG`
--
ALTER TABLE `TBLOG`
  MODIFY `CODIGOLOG` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=112;

--
-- AUTO_INCREMENT for table `TBMOVIMENTACAO`
--
ALTER TABLE `TBMOVIMENTACAO`
  MODIFY `NUMLANCTO` mediumint(6) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=86397;

--
-- AUTO_INCREMENT for table `TBMUNICIPIO`
--
ALTER TABLE `TBMUNICIPIO`
  MODIFY `CODIGOMUNICIPIO` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=12;

--
-- AUTO_INCREMENT for table `TBOBRIGACOES`
--
ALTER TABLE `TBOBRIGACOES`
  MODIFY `CODIGOOBRIGACAO` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=47;

--
-- AUTO_INCREMENT for table `TBORIGEMOBRIGACAO`
--
ALTER TABLE `TBORIGEMOBRIGACAO`
  MODIFY `CODIGOORIGEM` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=5;

--
-- AUTO_INCREMENT for table `TBPERIODICIDADE`
--
ALTER TABLE `TBPERIODICIDADE`
  MODIFY `CODIGOPERIODICIDADE` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=6;

--
-- AUTO_INCREMENT for table `TBPRODUTO`
--
ALTER TABLE `TBPRODUTO`
  MODIFY `CODIGOPRODUTO` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=16;

--
-- AUTO_INCREMENT for table `TBSETOR`
--
ALTER TABLE `TBSETOR`
  MODIFY `CODIGOSETOR` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=10;

--
-- AUTO_INCREMENT for table `TBSINDICATO`
--
ALTER TABLE `TBSINDICATO`
  MODIFY `CODIGOSINDICATO` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=47;

--
-- AUTO_INCREMENT for table `TBSITUACAO`
--
ALTER TABLE `TBSITUACAO`
  MODIFY `CODIGOSITUACAO` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=8;

--
-- AUTO_INCREMENT for table `TBSTATUS`
--
ALTER TABLE `TBSTATUS`
  MODIFY `COD_STATUS` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=5;

--
-- AUTO_INCREMENT for table `TBSUBPRODUTO`
--
ALTER TABLE `TBSUBPRODUTO`
  MODIFY `CODIGOSUBPRODUTO` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=6;

--
-- AUTO_INCREMENT for table `TBTIPOFATURAMENTO`
--
ALTER TABLE `TBTIPOFATURAMENTO`
  MODIFY `CODIGOTPFATURAMENTO` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=5;

--
-- AUTO_INCREMENT for table `TBTIPOOBRIGACAO`
--
ALTER TABLE `TBTIPOOBRIGACAO`
  MODIFY `CODIGOTIPOOBRIGACAO` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=4;

--
-- AUTO_INCREMENT for table `TBTRIBUTACAO`
--
ALTER TABLE `TBTRIBUTACAO`
  MODIFY `CODIGOTRIBUTACAO` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=11;

--
-- AUTO_INCREMENT for table `TBUSUARIO`
--
ALTER TABLE `TBUSUARIO`
  MODIFY `CODIGO_USUARIO` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=868;
COMMIT;

