-- Active: 1706276672210@@127.0.0.1@3306@agebd

DROP TABLE IF EXISTS TBBOLETO;

DROP TABLE IF EXISTS TBBOLETOEMAILXHISTORICO;

DROP TABLE IF EXISTS TBBOLETOXHISTORICOS;

DROP TABLE IF EXISTS TBCENTROCUSTO;

DROP TABLE IF EXISTS TBCOLABORADOR;

DROP TABLE IF EXISTS TBCOLABORADOR_FUNCAO;

DROP TABLE IF EXISTS TBCOMPXOBRIG;

DROP TABLE IF EXISTS TBEMPRESA;

DROP TABLE IF EXISTS TBEMPRESAPRODUTO;

DROP TABLE IF EXISTS TBEMPRESAUSUARIO;

DROP TABLE IF EXISTS TBEMPRESAXARQUIVOS;

DROP TABLE IF EXISTS TBEMPRESAXCCEMAIL;

DROP TABLE IF EXISTS TBEMPRESA_IMPORTACOES;

DROP TABLE IF EXISTS TBEMPRESA_OBRIGACOES;

DROP TABLE IF EXISTS TBEMPRESA_SINDICATO;

DROP TABLE IF EXISTS TBESFERAOBRIGACAO;

DROP TABLE IF EXISTS TBFORNEC;

DROP TABLE IF EXISTS TBFORNECEDOR;

DROP TABLE IF EXISTS TBFORNECEDORX;

DROP TABLE IF EXISTS TBINDICEREAJUSTE;

DROP TABLE IF EXISTS TBLOG;

DROP TABLE IF EXISTS TBMOVIMENTACAO;

DROP TABLE IF EXISTS TBMUNICIPIO;

DROP TABLE IF EXISTS TBOBRIGACOES;

DROP TABLE IF EXISTS TBOBRIGACOESMENSAL;

DROP TABLE IF EXISTS TBORIGEMOBRIGACAO;

DROP TABLE IF EXISTS TBPERIODICIDADE;

DROP TABLE IF EXISTS TBPLANOCONTAS;

DROP TABLE IF EXISTS TBPLCONTA;

DROP TABLE IF EXISTS TBPRODUTO;

DROP TABLE IF EXISTS TBPRODUTOSUBPRODUTO;

DROP TABLE IF EXISTS TBRESPONSAVEL_EMPRESA;

DROP TABLE IF EXISTS TBSETOR;

DROP TABLE IF EXISTS TBSETORFTP;

DROP TABLE IF EXISTS TBSINDICATO;

DROP TABLE IF EXISTS TBSITUACAO;

DROP TABLE IF EXISTS TBSTATUS;

DROP TABLE IF EXISTS TBSUBPRODUTO;

DROP TABLE IF EXISTS TBTEMP;

DROP TABLE IF EXISTS TBTIPOCERTIFICADO;

DROP TABLE IF EXISTS TBTIPOFATURAMENTO;

DROP TABLE IF EXISTS TBTIPOOBRIGACAO;

DROP TABLE IF EXISTS TBTRIBUTACAO;

DROP TABLE IF EXISTS TBUSUARIO;

DROP TABLE IF EXISTS TBBANCO;

DROP TABLE IF EXISTS TBBANCOEMPRESA;

DROP TABLE IF EXISTS TBCNAE;

CREATE TABLE TBBOLETO (
    COD_BOLETO int(11) NOT NULL,
    COD_EMPRESA int(11) DEFAULT NULL,
    STATUS int(11) DEFAULT '1',
    DATAREGISTRO datetime DEFAULT NULL,
    COD_USUARIO varchar(45) COLLATE latin1_general_ci DEFAULT NULL,
    DATACANCELAMENTO datetime DEFAULT NULL,
    COD_USUARIOCANCELAMENTO int(11) DEFAULT NULL
) ENGINE = InnoDB DEFAULT CHARSET = latin1 COLLATE = latin1_general_ci;

CREATE TABLE TBBOLETOEMAILXHISTORICO (
    CODTBBOLETOEMAILXHISTORICO int(11) NOT NULL,
    CODEMPRESA int(11) DEFAULT NULL,
    DATAREGISTRO datetime DEFAULT NULL,
    COMPETENCIA varchar(45) COLLATE latin1_general_ci DEFAULT NULL,
    DE varchar(4000) COLLATE latin1_general_ci DEFAULT NULL,
    CODUSUARIO int(11) DEFAULT NULL,
    PARA varchar(4000) COLLATE latin1_general_ci DEFAULT NULL,
    CC varchar(4000) COLLATE latin1_general_ci DEFAULT NULL
) ENGINE = InnoDB DEFAULT CHARSET = latin1 COLLATE = latin1_general_ci;

CREATE TABLE TBBOLETOXHISTORICOS (
    COD_BOLETOXHISTORICOS int(11) NOT NULL,
    COD_EMPRESA int(11) DEFAULT NULL,
    COD_STATUS int(11) DEFAULT NULL,
    OBS text COLLATE latin1_general_ci,
    DATAREGISTRO datetime DEFAULT NULL,
    COD_USUARIO int(11) DEFAULT NULL,
    FLAG int(11) DEFAULT NULL,
    COD_BOLETO int(11) DEFAULT NULL
) ENGINE = InnoDB DEFAULT CHARSET = latin1 COLLATE = latin1_general_ci;

CREATE TABLE TBCENTROCUSTO (
    CODIGOEMPRESA int(11) NOT NULL DEFAULT '0',
    CODIGOCCUSTO varchar(8) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
    DESCRICAOCCUSTO varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
    TPLANCAMENTO varchar(1) COLLATE utf8_unicode_ci DEFAULT NULL,
    TIPO varchar(1) COLLATE utf8_unicode_ci DEFAULT NULL,
    CCSUPERIOR varchar(8) COLLATE utf8_unicode_ci DEFAULT NULL,
    SITUACAO varchar(1) COLLATE utf8_unicode_ci DEFAULT NULL
) ENGINE = MyISAM DEFAULT CHARSET = utf8 COLLATE = utf8_unicode_ci;

CREATE TABLE TBCOLABORADOR (
    CODIGOCOLABORADOR mediumint(11) NOT NULL,
    NOMECOLABORADOR varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
    EMAILCOLABORADOR varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
    LOGINCOLABORADOR varchar(20) COLLATE utf8_unicode_ci DEFAULT NULL,
    SENHACOLABORADOR varchar(20) COLLATE utf8_unicode_ci DEFAULT NULL,
    CCUSTOCOLABORADOR varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
    DVGCOLABORADOR date DEFAULT NULL,
    DVLCOLABORADOR date DEFAULT NULL
) ENGINE = MyISAM DEFAULT CHARSET = utf8 COLLATE = utf8_unicode_ci;

CREATE TABLE TBCOLABORADOR_FUNCAO (
    CODIGOCOLABORADOR int(11) DEFAULT NULL,
    CODIGOFUNCAO int(11) DEFAULT NULL
) ENGINE = MyISAM DEFAULT CHARSET = utf8 COLLATE = utf8_unicode_ci;

CREATE TABLE TBCOMPXOBRIG (
    CODCOMPXOBRIG int(11) NOT NULL,
    CODOBRIGACAO int(11) NOT NULL,
    CODCOMPETENCIA int(11) NOT NULL
) ENGINE = MyISAM DEFAULT CHARSET = utf8 COLLATE = utf8_unicode_ci;

CREATE TABLE TBEMPRESA (
    CODIGOEMPRESA int(11) NOT NULL,
    RAZAOSOCIAL varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
    NOMEFANTASIA varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
    RESUMIDO varchar(30) COLLATE utf8_unicode_ci DEFAULT NULL,
    CNPJ varchar(18) COLLATE utf8_unicode_ci DEFAULT NULL,
    INSCESTADUAL varchar(18) COLLATE utf8_unicode_ci DEFAULT NULL,
    INSCMUNICIPAL varchar(18) COLLATE utf8_unicode_ci DEFAULT NULL,
    CODIGOMUNICIPIO int(6) DEFAULT NULL,
    ENDERECOCNPJ varchar(200) COLLATE utf8_unicode_ci DEFAULT NULL,
    BAIRROCNPJ varchar(60) COLLATE utf8_unicode_ci DEFAULT NULL,
    CIDADECNPJ varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
    CEPCNPJ varchar(8) COLLATE utf8_unicode_ci DEFAULT NULL,
    UFCNPJ char(2) COLLATE utf8_unicode_ci DEFAULT NULL,
    CODIGOSTATUS decimal(4, 0) DEFAULT NULL,
    DATACNPJ date DEFAULT NULL,
    CODIGOCNAE char(10) COLLATE utf8_unicode_ci DEFAULT NULL,
    ENDERECO varchar(200) COLLATE utf8_unicode_ci DEFAULT NULL,
    BAIRRO varchar(60) COLLATE utf8_unicode_ci DEFAULT NULL,
    CIDADE varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
    CEP varchar(8) COLLATE utf8_unicode_ci DEFAULT NULL,
    UF char(2) COLLATE utf8_unicode_ci DEFAULT NULL,
    OBSERVACAO varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
    SITE varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
    DUA date DEFAULT NULL,
    IDUA decimal(8, 0) DEFAULT NULL,
    SITUACAO char(1) COLLATE utf8_unicode_ci DEFAULT NULL,
    DVG date DEFAULT NULL,
    DVL date DEFAULT NULL,
    CAPITALSOCIAL decimal(10, 0) DEFAULT NULL,
    CODIGOMATRIZ decimal(6, 0) DEFAULT NULL,
    IR char(1) COLLATE utf8_unicode_ci DEFAULT NULL,
    CODIGOTRIBUTACAO int(11) DEFAULT NULL,
    PISCOFINSCUMULATIVO varchar(2) COLLATE utf8_unicode_ci DEFAULT NULL,
    CODIGOPATRONAL decimal(4, 0) DEFAULT NULL,
    CODIGOOBREIRO decimal(4, 0) DEFAULT NULL,
    RESPONSAVELRECEITAFEDERAL varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
    CPFRESPONSAVELRECEITA varchar(14) COLLATE utf8_unicode_ci DEFAULT NULL,
    DTVIGENCIACERTDIGITAL date DEFAULT NULL,
    DTVALIDADECERTDIGITAL date DEFAULT NULL,
    DTVALIDADEPROCURACAOAGE date DEFAULT NULL,
    SenhaFicus varchar(15) COLLATE utf8_unicode_ci DEFAULT NULL,
    SenhaExtratoInss varchar(15) COLLATE utf8_unicode_ci DEFAULT NULL,
    email varchar(200) COLLATE utf8_unicode_ci DEFAULT NULL,
    deemail varchar(200) COLLATE utf8_unicode_ci DEFAULT NULL,
    MOVPROTOCOLO varchar(200) COLLATE utf8_unicode_ci DEFAULT NULL
) ENGINE = MyISAM DEFAULT CHARSET = utf8 COLLATE = utf8_unicode_ci;

CREATE TABLE TBEMPRESAPRODUTO (
    CODIGOEMPRESA int(11) NOT NULL DEFAULT '0',
    CODIGOPRODUTO int(11) NOT NULL DEFAULT '0',
    DUA date DEFAULT NULL,
    SITUACAO varchar(1) COLLATE utf8_unicode_ci DEFAULT NULL,
    DVL date DEFAULT '1970-01-01',
    DVG date NOT NULL DEFAULT '1970-01-01',
    IDUA int(11) DEFAULT NULL,
    VALORFATURAMENTO float(15, 2) DEFAULT NULL,
    CODIGOEMPRESAPROVEDORA int(11) DEFAULT NULL,
    CODIGOTPFATURAMENTO int(11) DEFAULT NULL,
    CODIGOINDICEREAJUSTE int(11) DEFAULT NULL,
    MESREAJUSTE int(11) DEFAULT NULL,
    DIAVENCIMENTO int(11) DEFAULT NULL,
    MESATUALOUSEGUINTE varchar(1) COLLATE utf8_unicode_ci DEFAULT NULL,
    CODIGOEMPRESAFATURADORA int(11) DEFAULT NULL,
    AGRUPAPRODUTOS varchar(1) COLLATE utf8_unicode_ci DEFAULT NULL,
    FATURAPORUNIDADE varchar(1) COLLATE utf8_unicode_ci DEFAULT NULL,
    EMITENF varchar(1) COLLATE utf8_unicode_ci DEFAULT NULL
) ENGINE = MyISAM DEFAULT CHARSET = utf8 COLLATE = utf8_unicode_ci;

CREATE TABLE TBEMPRESAUSUARIO (
    CODIGO_USUARIO int(11) NOT NULL DEFAULT '0',
    CODIGOPRODUTO int(11) NOT NULL DEFAULT '0',
    CODIGOEMPRESA int(11) NOT NULL DEFAULT '0',
    CODIGOSUBPRODUTO int(11) NOT NULL DEFAULT '0',
    SITUACAO varchar(1) COLLATE utf8_unicode_ci DEFAULT NULL,
    DVG date DEFAULT NULL,
    DVL date DEFAULT NULL
) ENGINE = MyISAM DEFAULT CHARSET = utf8 COLLATE = utf8_unicode_ci;

CREATE TABLE TBEMPRESAXARQUIVOS (
    COD_EMPRESAXARQUIVOS int(11) NOT NULL,
    COD_EMPRESA int(11) DEFAULT NULL,
    ANO int(11) DEFAULT NULL,
    MES int(11) DEFAULT NULL,
    NOMEARQUIVO varchar(400) COLLATE latin1_general_ci DEFAULT NULL,
    EXTENSAO char(3) COLLATE latin1_general_ci DEFAULT NULL,
    TAMANHO int(11) DEFAULT NULL,
    URL text COLLATE latin1_general_ci,
    DATAREGISTRO datetime DEFAULT NULL
) ENGINE = InnoDB DEFAULT CHARSET = latin1 COLLATE = latin1_general_ci;

CREATE TABLE TBEMPRESAXCCEMAIL (
    COD_CCEMAIL int(11) NOT NULL,
    EMAIL_CC varchar(200) COLLATE latin1_general_ci DEFAULT NULL,
    COD_EMPRESA int(11) DEFAULT NULL
) ENGINE = InnoDB DEFAULT CHARSET = latin1 COLLATE = latin1_general_ci;

CREATE TABLE TBEMPRESA_IMPORTACOES (
    CODIGOEMPRESA int(11) NOT NULL,
    PERIODO datetime DEFAULT NULL,
    STATUS varchar(45) COLLATE latin1_general_ci DEFAULT NULL,
    IDDUA int(11) DEFAULT NULL,
    DUA datetime DEFAULT NULL
) ENGINE = InnoDB DEFAULT CHARSET = latin1 COLLATE = latin1_general_ci;

CREATE TABLE TBEMPRESA_OBRIGACOES (
    CODIGOEMPRESA int(11) NOT NULL DEFAULT '0',
    CODIGOOBRIGACAO int(11) NOT NULL DEFAULT '0',
    DIALIMITEENVIO int(11) DEFAULT NULL,
    MESESPARAENTREGA int(11) DEFAULT NULL,
    DVG date DEFAULT NULL,
    DVL date DEFAULT NULL,
    IDDUA int(11) DEFAULT NULL,
    DUA date DEFAULT NULL
) ENGINE = MyISAM DEFAULT CHARSET = utf8 COLLATE = utf8_unicode_ci;

CREATE TABLE TBEMPRESA_SINDICATO (
    CODIGOEMPRESA int(11) NOT NULL DEFAULT '0',
    CODIGOSINDICATO int(11) NOT NULL DEFAULT '0',
    DVL date DEFAULT NULL,
    IDUA int(11) DEFAULT NULL,
    DUA date DEFAULT NULL
) ENGINE = MyISAM DEFAULT CHARSET = utf8 COLLATE = utf8_unicode_ci;

CREATE TABLE TBESFERAOBRIGACAO (
    CODIGOESFERAOBRIGACAO int(11) NOT NULL,
    DESCRICAOESFERAOBRIGACAO varchar(30) COLLATE utf8_unicode_ci DEFAULT NULL
) ENGINE = MyISAM DEFAULT CHARSET = utf8 COLLATE = utf8_unicode_ci;

CREATE TABLE TBFORNEC (
    empresa int(11) NOT NULL DEFAULT '0',
    CodigoFornecedor int(11) NOT NULL DEFAULT '0',
    RazaoSocial varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
    FisicaouJuridica varchar(1) COLLATE utf8_unicode_ci DEFAULT NULL,
    CNPJouCPF varchar(30) COLLATE utf8_unicode_ci DEFAULT NULL,
    endereco int(11) DEFAULT NULL,
    bairro int(11) DEFAULT NULL,
    cidade int(11) DEFAULT NULL,
    uf int(11) DEFAULT NULL,
    cep int(11) DEFAULT NULL,
    codigobanco int(11) DEFAULT NULL,
    agencia int(11) DEFAULT NULL,
    digitoag int(11) DEFAULT NULL,
    contacorrente int(11) DEFAULT NULL,
    digitoconta int(11) DEFAULT NULL,
    CodigoCCusto varchar(5) COLLATE utf8_unicode_ci DEFAULT NULL,
    CodigoConta int(11) DEFAULT NULL
) ENGINE = MyISAM DEFAULT CHARSET = utf8 COLLATE = utf8_unicode_ci;

CREATE TABLE TBFORNECEDOR (
    CODIGOEMPRESA decimal(6, 0) NOT NULL,
    CODIGOFORNECEDOR decimal(6, 0) NOT NULL,
    NOMEFORNECEDOR varchar(50) COLLATE utf8_unicode_ci NOT NULL,
    TIPO char(1) COLLATE utf8_unicode_ci NOT NULL,
    CNPJCPF varchar(14) COLLATE utf8_unicode_ci DEFAULT NULL,
    ENDERECO varchar(160) COLLATE utf8_unicode_ci DEFAULT NULL,
    BAIRRO varchar(80) COLLATE utf8_unicode_ci DEFAULT NULL,
    CIDADE varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
    UF char(2) COLLATE utf8_unicode_ci DEFAULT NULL,
    CEP decimal(8, 0) DEFAULT NULL,
    CODIGOBANCO decimal(4, 0) DEFAULT NULL,
    AGENCIA varchar(10) COLLATE utf8_unicode_ci DEFAULT NULL,
    DIGITOAG char(2) COLLATE utf8_unicode_ci DEFAULT NULL,
    CONTACORRENTE varchar(10) COLLATE utf8_unicode_ci DEFAULT NULL,
    DIGITOCONTA char(2) COLLATE utf8_unicode_ci DEFAULT NULL,
    CODIGOCCUSTO varchar(8) COLLATE utf8_unicode_ci DEFAULT NULL,
    CODIGOPLANO varchar(10) COLLATE utf8_unicode_ci DEFAULT NULL
) ENGINE = MyISAM DEFAULT CHARSET = utf8 COLLATE = utf8_unicode_ci;

CREATE TABLE TBFORNECEDORX (
    `Codigo Fornecedor` int(11) NOT NULL,
    `Razao Social` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
    `Fisica ou Juridica` varchar(1) COLLATE utf8_unicode_ci DEFAULT NULL,
    `CNPJ ou CPF` varchar(30) COLLATE utf8_unicode_ci DEFAULT NULL,
    `Codigo Conta Pl de Conta` int(11) DEFAULT NULL,
    `CodigoCCusto` varchar(5) COLLATE utf8_unicode_ci DEFAULT NULL
) ENGINE = MyISAM DEFAULT CHARSET = utf8 COLLATE = utf8_unicode_ci;

CREATE TABLE TBINDICEREAJUSTE (
    CODIGOINDICEREAJUSTE int(11) NOT NULL,
    DESCRICAOINDICEREAJUSTE varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL
) ENGINE = MyISAM DEFAULT CHARSET = utf8 COLLATE = utf8_unicode_ci;

CREATE TABLE TBLOG (
    CODIGOLOG int(11) NOT NULL,
    DATALOG date DEFAULT NULL,
    USUARIOUPLOAD int(11) DEFAULT NULL,
    ARQUIVO varchar(200) COLLATE utf8_unicode_ci DEFAULT NULL,
    DESCRICAOARQUIVO varchar(300) COLLATE utf8_unicode_ci DEFAULT NULL,
    CODIGOEMPRESA int(11) DEFAULT NULL,
    CODIGOPRODUTO int(11) DEFAULT NULL,
    CODIGOSUBPRODUTO int(11) DEFAULT NULL,
    USUARIODOWN int(11) DEFAULT NULL
) ENGINE = MyISAM DEFAULT CHARSET = utf8 COLLATE = utf8_unicode_ci;

CREATE TABLE TBMOVIMENTACAO (
    NUMLANCTO mediumint(6) NOT NULL,
    IDUSUARIOLANCTO int(11) DEFAULT NULL,
    CODIGOEMPRESA int(8) DEFAULT NULL,
    CODIGOSITUACAO int(8) DEFAULT NULL,
    DATALANCTO date DEFAULT NULL,
    CODIGOCCUSTO varchar(8) COLLATE utf8_unicode_ci DEFAULT NULL,
    CODIGOPLANO varchar(10) COLLATE utf8_unicode_ci DEFAULT NULL,
    CODIGOFORNECEDOR int(8) DEFAULT NULL,
    OBSERVACAO varchar(200) COLLATE utf8_unicode_ci DEFAULT NULL,
    DOCUMENTO varchar(20) COLLATE utf8_unicode_ci DEFAULT NULL,
    DATAMOVIMENTO date DEFAULT NULL,
    VALOR decimal(8, 2) DEFAULT NULL,
    IDUA int(11) DEFAULT NULL,
    DUA datetime DEFAULT NULL,
    CODIGOBANCO int(11) DEFAULT NULL
) ENGINE = MyISAM DEFAULT CHARSET = utf8 COLLATE = utf8_unicode_ci;

CREATE TABLE TBMUNICIPIO (
    CODIGOMUNICIPIO int(11) NOT NULL,
    DESCRICAOMUNICIPIO varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
    UF varchar(2) COLLATE utf8_unicode_ci DEFAULT NULL
) ENGINE = MyISAM DEFAULT CHARSET = utf8 COLLATE = utf8_unicode_ci;

CREATE TABLE TBOBRIGACOES (
    CODIGOOBRIGACAO int(11) NOT NULL,
    DESCRICAOOBRIGACAO varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
    TIPOOBRIGACAO int(11) DEFAULT NULL,
    ESFERAOBRIGACAO int(11) DEFAULT NULL,
    ORIGEMOBRIGACAO int(11) DEFAULT NULL,
    PERIODICIDADE int(11) DEFAULT NULL,
    IDUA int(11) DEFAULT NULL,
    DUA date DEFAULT NULL,
    DIASLIMITE int(11) DEFAULT '20'
) ENGINE = MyISAM DEFAULT CHARSET = utf8 COLLATE = utf8_unicode_ci;

CREATE TABLE TBOBRIGACOESMENSAL (
    COMPETENCIA int(11) NOT NULL,
    CODIGOEMPRESA int(11) NOT NULL,
    CODIGOOBRIGACAO int(11) NOT NULL,
    STATUS char(1) CHARACTER SET latin1 DEFAULT NULL,
    IDUATICAR int(11) DEFAULT NULL,
    DTTICAR timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    ANO int(11) NOT NULL,
    MOTIVO text CHARACTER SET latin1
) ENGINE = MyISAM DEFAULT CHARSET = utf8 COLLATE = utf8_unicode_ci;

CREATE TABLE TBORIGEMOBRIGACAO (
    CODIGOORIGEM int(11) NOT NULL,
    DESCRICAOORIGEM varchar(30) COLLATE utf8_unicode_ci DEFAULT NULL
) ENGINE = MyISAM DEFAULT CHARSET = utf8 COLLATE = utf8_unicode_ci;

CREATE TABLE TBPERIODICIDADE (
    CODIGOPERIODICIDADE int(11) NOT NULL,
    DESCRICAOPERIODICIDADE varchar(30) COLLATE utf8_unicode_ci DEFAULT NULL
) ENGINE = MyISAM DEFAULT CHARSET = utf8 COLLATE = utf8_unicode_ci;

CREATE TABLE TBPLANOCONTAS (
    CODIGOEMPRESA int(11) NOT NULL DEFAULT '0',
    CODIGOPLANO varchar(10) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
    DESCRICAOPLANO varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
    TIPOPLANO varchar(1) COLLATE utf8_unicode_ci DEFAULT NULL,
    PLANOPAI varchar(10) COLLATE utf8_unicode_ci DEFAULT NULL
) ENGINE = MyISAM DEFAULT CHARSET = utf8 COLLATE = utf8_unicode_ci;

CREATE TABLE TBPLCONTA (
    CODIGOEMPRESA int(11) NOT NULL DEFAULT '0',
    CodigoConta int(11) NOT NULL DEFAULT '0',
    Descricao varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
    TIPO varchar(1) COLLATE utf8_unicode_ci DEFAULT NULL,
    SUP int(11) DEFAULT NULL
) ENGINE = MyISAM DEFAULT CHARSET = utf8 COLLATE = utf8_unicode_ci;

CREATE TABLE TBPRODUTO (
    CODIGOPRODUTO int(11) NOT NULL,
    DESCRICAOPRODUTO varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
    DVL date DEFAULT NULL
) ENGINE = MyISAM DEFAULT CHARSET = utf8 COLLATE = utf8_unicode_ci;

CREATE TABLE TBPRODUTOSUBPRODUTO (
    CODIGOPRODUTO int(11) NOT NULL DEFAULT '0',
    CODIGOSUBPRODUTO int(11) NOT NULL DEFAULT '0'
) ENGINE = MyISAM DEFAULT CHARSET = utf8 COLLATE = utf8_unicode_ci;

CREATE TABLE TBRESPONSAVEL_EMPRESA (
    CODIGOEMPRESA int(11) NOT NULL DEFAULT '0',
    CODIGOCOLABORADOR int(11) NOT NULL DEFAULT '0',
    CODIGOFUNCAO int(11) DEFAULT NULL,
    DVGRESPONSAVEL datetime DEFAULT NULL,
    DVLRESPONSAVEL datetime DEFAULT NULL
) ENGINE = MyISAM DEFAULT CHARSET = utf8 COLLATE = utf8_unicode_ci;

CREATE TABLE TBSETOR (
    CODIGOSETOR int(11) NOT NULL,
    NOMESETOR varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL
) ENGINE = MyISAM DEFAULT CHARSET = utf8 COLLATE = utf8_unicode_ci;

CREATE TABLE TBSETORFTP (
    CODIGOSETOR int(11) NOT NULL DEFAULT '0',
    NOMEPASTA varchar(50) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
    DVL date DEFAULT NULL
) ENGINE = MyISAM DEFAULT CHARSET = utf8 COLLATE = utf8_unicode_ci;

CREATE TABLE TBSINDICATO (
    CODIGOSINDICATO int(11) NOT NULL,
    DESCRICAOSINDICATO varchar(80) COLLATE utf8_unicode_ci DEFAULT NULL,
    TIPOSINDICATO varchar(1) COLLATE utf8_unicode_ci DEFAULT NULL,
    DATADISSIDIO int(11) DEFAULT NULL,
    IDUA int(11) DEFAULT NULL,
    DUA date DEFAULT NULL
) ENGINE = MyISAM DEFAULT CHARSET = utf8 COLLATE = utf8_unicode_ci;

CREATE TABLE TBSITUACAO (
    CODIGOSITUACAO int(11) NOT NULL,
    DESCRICAOSITUACAO varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL
) ENGINE = MyISAM DEFAULT CHARSET = utf8 COLLATE = utf8_unicode_ci;

CREATE TABLE TBSTATUS (
    COD_STATUS int(11) NOT NULL,
    NOME varchar(400) COLLATE latin1_general_ci DEFAULT NULL
) ENGINE = InnoDB DEFAULT CHARSET = latin1 COLLATE = latin1_general_ci;

CREATE TABLE TBSUBPRODUTO (
    CODIGOSUBPRODUTO int(11) NOT NULL,
    DESCRICAOSUBPRODUTO varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL
) ENGINE = MyISAM DEFAULT CHARSET = utf8 COLLATE = utf8_unicode_ci;

CREATE TABLE TBTEMP (
    COD int(11) NOT NULL,
    RAZAOSOCIAL varchar(123) COLLATE utf8_unicode_ci DEFAULT NULL,
    Inicio datetime DEFAULT NULL,
    certdig datetime DEFAULT NULL,
    fimcertdiig datetime DEFAULT NULL,
    fimprocuracao datetime DEFAULT NULL
) ENGINE = MyISAM DEFAULT CHARSET = utf8 COLLATE = utf8_unicode_ci;

CREATE TABLE TBTIPOCERTIFICADO (
    IDTIPOCERT int(11) NOT NULL,
    DESCRICAOTIPOCERT varchar(45) COLLATE latin1_general_ci NOT NULL
) ENGINE = InnoDB DEFAULT CHARSET = latin1 COLLATE = latin1_general_ci;

CREATE TABLE TBTIPOFATURAMENTO (
    CODIGOTPFATURAMENTO int(11) NOT NULL,
    DESCRICAOTPFATURAMENTO varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL
) ENGINE = MyISAM DEFAULT CHARSET = utf8 COLLATE = utf8_unicode_ci;

CREATE TABLE TBTIPOOBRIGACAO (
    CODIGOTIPOOBRIGACAO int(11) NOT NULL,
    DESCRICAOTIPOOBRIGACAO varchar(30) COLLATE utf8_unicode_ci DEFAULT NULL
) ENGINE = MyISAM DEFAULT CHARSET = utf8 COLLATE = utf8_unicode_ci;

CREATE TABLE TBTRIBUTACAO (
    CODIGOTRIBUTACAO int(11) NOT NULL,
    DESCRICAOTRIBUTACAO varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL
) ENGINE = MyISAM DEFAULT CHARSET = utf8 COLLATE = utf8_unicode_ci;

CREATE TABLE TBUSUARIO (
    CODIGO_USUARIO int(11) NOT NULL,
    NOME varchar(200) COLLATE utf8_unicode_ci DEFAULT NULL,
    LOGIN varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
    SENHA varchar(10) COLLATE utf8_unicode_ci DEFAULT NULL,
    TIPO_USUARIO varchar(1) COLLATE utf8_unicode_ci DEFAULT NULL,
    DVG date DEFAULT NULL,
    DVL date DEFAULT NULL,
    EMAIL1 varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
    EMAIL2 varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
    FONECOM varchar(16) COLLATE utf8_unicode_ci DEFAULT NULL,
    FONERES varchar(16) COLLATE utf8_unicode_ci DEFAULT NULL,
    FONECEL varchar(16) COLLATE utf8_unicode_ci DEFAULT NULL,
    FONEFAX varchar(16) COLLATE utf8_unicode_ci DEFAULT NULL,
    OBSERVACAO varchar(200) COLLATE utf8_unicode_ci DEFAULT NULL,
    NASCIMENTO date DEFAULT NULL
) ENGINE = MyISAM DEFAULT CHARSET = utf8 COLLATE = utf8_unicode_ci;

CREATE TABLE TBBANCO (
    CODIGOBANCO int(11) NOT NULL DEFAULT '0',
    NOMEBANCO varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL
) ENGINE = MyISAM DEFAULT CHARSET = utf8 COLLATE = utf8_unicode_ci;

CREATE TABLE TBBANCOEMPRESA (
    CODIGOEMPRESA int(11) NOT NULL DEFAULT '0',
    CODIGOBANCO int(11) NOT NULL DEFAULT '0',
    DESCRICAOBANCO varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
    AGENCIA int(11) DEFAULT NULL,
    CONTA varchar(10) COLLATE utf8_unicode_ci DEFAULT NULL,
    DIGITO varchar(2) COLLATE utf8_unicode_ci DEFAULT NULL
) ENGINE = MyISAM DEFAULT CHARSET = utf8 COLLATE = utf8_unicode_ci;

CREATE TABLE TBCNAE (
  CODIGOCNAE CHAR(20) NOT NULL,
  DESCRICAOCNAE VARCHAR(100) NOT NULL,
  PRIMARY KEY (CODIGOCNAE)
) ENGINE=MyISAM DEFAULT CHARSET = utf8 COLLATE = utf8_unicode_ci;

