

SELECT
    e.CODIGOEMPRESA,
    e.RAZAOSOCIAL,
    e.CNPJ,
    e.CODIGOSTATUS,
    o.*
FROM TBEMPRESA e
INNER JOIN tbstatus s ON e.CODIGOSTATUS = s.COD_STATUS
INNER JOIN tbempresa_obrigacoes o ON e.CODIGOEMPRESA = o.CODIGOEMPRESA
WHERE s.COD_STATUS = 1
ORDER BY e.CODIGOEMPRESA DESC;


SELECT * FROM tbempresa e;

SELECT * FROM tbstatus s;
